# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

_chomp_path() {
    #local path=${1/${HOME}\// }
    local path=${1/${HOME}/ ~}
    path=${path//${HOME}}
    local last=${path} sedout= count=0 path2=
    #bash is dumb, "${#path//[^'/']/}" fails.
    #sedout="${path//[^'/']/}"
    sedout=(${path//\// })
    count=${#sedout[@]}
    echo ${last}
}

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# Combine multiline commands into one in history
shopt -s cmdhist

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
#HISTSIZE=1000
#HISTFILESIZE=2000

unset HISTSIZE
unset HISTFILESIZE
HISTIGNORE="&:ls:[bf]g:exit:..:l:dow"
HOSTNAME="$(hostname)"
HOSTNAME_SHORT="${HOSTNAME%%.*}"
HISTFILE="${HOME}/.history/$(date -u +%Y/%m/%d.%H.%M.%S)_${HOSTNAME_SHORT}_$$"
mkdir -p "$(dirname "$HISTFILE")"
histgrep () {
    grep --color=auto -r "$@" ~/.history
    history | grep --color=auto "$@"
}


# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color|*-256color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
#force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=
    fi
fi

if [ "$color_prompt" = yes ]; then
    #PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
    PS1='\[\033[01;32m\]# `date +"%Y.%m.%d %R"` $(pwd)\n\$\[\033[00m\] '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

complete -f -X '!*.pdf' mupdf
complete -f -X '!*.pdf' pdfviewer
complete -f -X '!*.corr' ramaplot
complete -f -X '!*.gp' gp
complete -f -X '!*.gp' gpp
complete -f -X '!*.pdf' cn

# colored GCC warnings and errors
#export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

###################################################################
PROMPT_DIRTRIM=2
PS1='\[\e[38;5;172m\]# \h\[\e[38;5;245m\]: \[\e[38;5;5m\]`_chomp_path $(pwd)`\n\[\e[38;5;202m\]⟫\[\e[00m\] '
###################################################################

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi
calc(){ echo $@ | julia;}
shopt -s extglob
#export VIMRUNTIME=/usr/share/vim/vimcurrent
alias emerillon='export CLUTTER_VBLANK=none && emerillon'
man () { yelp "man:$@"; }
export SVNROOT=svn+ichiport://cdalgicdir@88.255.97.68/home/svnroot

case "$TERM" in
    xterm*|rxvt*|screen*)
        bind '"\e[A": history-search-backward'
        bind '"\e[B": history-search-forward'
    ;;
esac

# added by Anaconda2 4.2.0 installer
export PATH="/home/cdalgicdir/anaconda2/bin:$PATH"
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib64
export PATH=$PATH:/usr/local/cuda/bin

## Up Arrow: search and complete from previous history
#bind '"\e[A": history-search-backward'
## Down Arrow: search and complete from next history
#bind '"\e[B": history-search-forward'
# Ctrl-v: (insert mode) switch to command mode and edit in vi
bind '"\C-v": "\ev"'
function gvim () { (/usr/bin/gvim -f "$@" &) }

#Automatically do an ls after each cd
cd() {
   builtin cd "$@"
   [[ $PWD == "$HOME/Downloads" ]] && ls -tr || ls
}

function pawk {
    local first="awk '{ if ( \$1 !~ /^[@|#]/) print "
    local last="}'"
    local cmd="${first}\$${1}${last}"
    eval $cmd
}

function dirawk {
    local cmd="awk '{split(\$1,a,\"/\");print a[1]}'"
    eval $cmd
}

alias alert_helper='history|tail -n1|sed -e "s/^\s*[0-9]\+\s*//" -e "s/;\s*alert$//"'
alias alert='notify-send -i /usr/share/icons/gnome/32x32/apps/gnome-terminal.png "[$?] $(alert_helper)"'
#export VIMRUNTIME=/usr/share/vim/vim74
export LC_TIME=en_GB.utf8
export EDITOR=vim
#export MMTSBDIR=$HOME/mmtsb
#source /home/soft/bashrc_extension_soft

# add /home/soft software
#GROMACS="/home/soft/gromacs/gromacs-4.6.7/inst/shared"
SOFT=$HOME/soft
TMUX=$SOFT/tmux/tmux-2.3
GNUPLOT=$SOFT/gnuplot/gnuplot-5.0.5-qt5
GROMACS=$SOFT/gromacs/gromacs-4.6.7
PLUMED=$SOFT/plumed/plumed-2.2.4
#VOTCA=$SOFT/votca/votca-1.2.4-fixed
VOTCA=$SOFT/votca/votca-1.3
export PATH=/home/cdalgicdir/anaconda/bin:$PATH
export PATH=$TMUX/bin:$SOFT/bin:$PATH
export PATH=$GNUPLOT/bin:$PATH
#export PATH=$TMUX/bin:$GNUPLOT/bin:$SOFT/bin:$PATH
source $GROMACS/bin/GMXRC.bash
export GMXLIB=$GROMACS/share/gromacs/top
source $VOTCA/bin/VOTCARC.bash
export PATH=$PATH:$PLUMED/bin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PLUMED/lib
export PLUMED_KERNEL=$PLUMED/lib/libplumedKernel.so
export PATH=$PATH:$HOME/soft/moltemplate/moltemplate/src
export MOLTEMPLATE_PATH=$HOME/soft/moltemplate/moltemplate/common
export PATH=$PATH:$HOME/soft/espressopp/espressopp/bin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/soft/espressopp/espressopp/lib
export PYTHONPATH=$PYTHONPATH:$HOME/soft/espressopp/espressopp/lib/python2.7/dist-packages
#export PATH=$HOME/progs/screen-4.2.1/bin:$PATH
alias diff-side-by-side='diff --side-by-side -W"`tput cols`"'
alias diff-side-by-side-changes='diff --side-by-side --suppress-common-lines -W"`tput cols`"'
#[ -r /home/cdalgicdir/.byobu/prompt ] && . /home/cdalgicdir/.byobu/prompt   #byobu-prompt#
#CDPATH=$CDPATH:~/remote
# get airline working 
export TERM=xterm-256color
#export TERM=screen-256color-bce
#export TERM=screen-256color
#so as not to be disturbed by Ctrl-S ctrl-Q in terminals:
stty -ixon

if [ -f ~/.bash_aliases_soft ]; then
    . ~/.bash_aliases_soft
fi

export PATH=$PATH:$SOFT/wham/bin
export LC_NUMERIC="en_US.UTF-8"
export PROMPT_COMMAND="history -a"
export PATH=$PATH:$HOME/.local/bin
export LESS='-R'
export LESSOPEN='|~/.lessfilter %s'
export PLUMED_VIMPATH=$PLUMED/lib/plumed/vim
