#! /user/bin/env bash

# export PATH="$HOME/anaconda3/bin:$PATH"
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib64
export PATH=$PATH:/usr/local/cuda/bin

SOFT=$HOME/soft
TMUX=$SOFT/tmux/tmux
# GNUPLOT=$SOFT/gnuplot/gnuplot-5.0.5_2
GNUPLOT=$SOFT/gnuplot/gnuplot-5.2.4
GROMACS=$SOFT/gromacs/gromacs-4.6.7
PLUMED=$SOFT/plumed/plumed-2.2.4
#VOTCA=$SOFT/votca/votca-1.2.4-fixed
# VOTCA=$SOFT/votca/votca-1.3
VIM=$SOFT/vim/vim-181113
MUPDF=$SOFT/mupdf/mupdf
export LD_LIBRARY_PATH=$MUPDF/lib:$LD_LIBRARY_PATH
# export PATH=$VIM/bin:$PATH
export PATH=$TMUX/bin:$SOFT/bin:$PATH
export PATH=$GNUPLOT/bin:$PATH
#export PATH=$TMUX/bin:$GNUPLOT/bin:$SOFT/bin:$PATH
source "$GROMACS/bin/GMXRC.bash"
export GMXLIB=$GROMACS/share/gromacs/top
# source $VOTCA/bin/VOTCARC.bash
export PATH=$PATH:$PLUMED/bin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PLUMED/lib
export PLUMED_KERNEL=$PLUMED/lib/libplumedKernel.so
export PATH=$PATH:$HOME/soft/moltemplate/moltemplate/src
# export MOLTEMPLATE_PATH=$HOME/soft/moltemplate/moltemplate/common
# export PATH=$PATH:$HOME/soft/espressopp/espressopp/bin
# export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/soft/espressopp/espressopp/lib
# export PYTHONPATH=$PYTHONPATH:$HOME/soft/espressopp/espressopp/lib/python2.7/dist-packages
export PATH=$PATH:$SOFT/wham/bin
export LC_NUMERIC="en_US.UTF-8"
export PROMPT_COMMAND="history -a"
export PATH=$PATH:$HOME/.local/bin
export LESS='-R'
export LESSOPEN='|~/.lessfilter %s'
export PLUMED_VIMPATH=$PLUMED/lib/plumed/vim
export PYTHONPATH=$PYTHONPATH:$HOME/simfiles/pylib
export PATH=/usr/local/texlive/2017/bin/x86_64-linux:$PATH
export MANPATH=/usr/local/texlive/2017/texmf-dist/doc/man:$MANPATH
export INFOPATH=/usr/local/texlive/2017/texmf-dist/doc/info:INFOPATH
# pyenv
export PATH="$HOME/.pyenv/bin:$PATH"
# eval "$(pyenv init -)"
# eval "$(pyenv virtualenv-init -)"
alias acpyenv='eval "$(pyenv init -)" && eval "$(pyenv virtualenv-init -)"'
export PYENV_VIRTUALENV_DISABLE_PROMPT=1
. /data/anaconda3/etc/profile.d/conda.sh
conda activate
# source $HOME/soft/fast-p/p
