#! /bin/bash

source_gromacs () {
    source $GROMACS/bin/GMXRC.bash
}

source_plumed () {
    export PATH=$PLUMED/bin:$PATH
    export LD_LIBRARY_PATH=$PLUMED/lib:$LD_LIBRARY_PATH
    export PLUMED_KERNEL=$PLUMED/lib/libplumedKernel.so
}

SOFT=$HOME/soft
#alias plumed-2.1.4="PLUMED=$SOFT/plumed/plumed-2.1.4 && source_plumed && GROMACS=$SOFT/gromacs/gromacs-4.6.7_plumed-2.1.4 && source_gromacs"
#alias plumed-2.2.1="PLUMED=$SOFT/plumed/plumed-2.2.1 && source_plumed && GROMACS=$SOFT/gromacs/gromacs-4.6.7_plumed-2.2.1 && source_gromacs"
alias plumed-2.1.3="PLUMED=$SOFT/plumed/plumed-2.1.3 && source_plumed && GROMACS=$SOFT/gromacs/gromacs-4.6.7_plumed-2.1.3 && source_gromacs"
alias plumed-2.2.2="PLUMED=$SOFT/plumed/plumed-2.2.2 && source_plumed && GROMACS=$SOFT/gromacs/gromacs-4.6.7_plumed-2.2.2 && source_gromacs"
alias plumed-2.2.4="PLUMED=$SOFT/plumed/plumed-2.2.4 && source_plumed && GROMACS=$SOFT/gromacs/gromacs-4.6.7_plumed-2.2.4 && source_gromacs"
alias plumed-2.2.5="PLUMED=$SOFT/plumed/plumed-2.2.5 && source_plumed && GROMACS=$SOFT/gromacs/gromacs-4.6.7_plumed-2.2.5 && source_gromacs"
alias plumed-2.3.0="PLUMED=$SOFT/plumed/plumed-2.3.0 && source_plumed && GROMACS=$SOFT/gromacs/gromacs-2016.1_plumed-2.3.0 && source_gromacs"
alias plumed-2.3.2="PLUMED=$SOFT/plumed/plumed-2.3.2 && source_plumed && GROMACS=$SOFT/gromacs/gromacs-2016.3_plumed-2.3.2 && source_gromacs"
alias plumed-2.4b="PLUMED=$SOFT/plumed/plumed-2.4b && source_plumed && GROMACS=$SOFT/gromacs/gromacs-2016.4_plumed-2.4b && source_gromacs"
alias gromacs-5.1.4="GROMACS=$SOFT/gromacs/gromacs-5.1.4 && source_gromacs"
# alias gromacs-2016.1="GROMACS=$SOFT/gromacs/gromacs-2016.1 && source_gromacs"
alias gromacs-2016.2="GROMACS=$SOFT/gromacs/gromacs-2016.2 && source_gromacs"
alias gromacs-2016.1_plumed-2.3.0="PLUMED=$SOFT/plumed/plumed-2.3.0 && source_plumed && GROMACS=$SOFT/gromacs/gromacs-2016.1_plumed-2.3.0 && source_gromacs"
