syntax enable
set background=dark
set guioptions-=T

if matchstr(expand("%"),".*\.md") != ""
    "colorscheme darkdevel
    "set guifont=Monofur\ 15
    colorscheme pencil
    set background=light
    set guifont=Courier\ Prime\ 15
    " Monofur, Monaco, Source Code Pro
    "set guifont=Ubuntu\ Mono\ 16
    :au BufRead *.tex set spell
    ":highlight SpellBad gui=underline guibg=NONE guifg=red
    :au BufRead *.md syn region mkdCode start="\[@" end="\]"
    ":au BufRead *.md syn region mkdRule matchgroup=mkdDelimiter start="\[@" end="\]"
elseif matchstr(expand("%"),".*\.tex") != ""
    "colorscheme corporation
    "set guifont=Inconsolata\ 15
    "colorscheme pencil
    colorscheme stylus
    "set guifont=Anonymous\ Pro\ 15
    "set guifont=Courier\ Prime\ 15
    set guifont=Deja\ Vu\ Sans\ Mono\ 15
    "set guifont=Cousine\ 15
    "set guifont=Fantasque\ Sans\ Mono\ 15
    "set guifont=Luxi\ Mono\ Regular\ 15
    "set guifont=Liberation\ Mono\ 15
    "set guifont=Ubuntu\ Mono\ 16
    "set guifont=Source\ Code\ Pro\ 16
    " Monofur, Monaco, Source Code Pro
    :au BufRead *.tex set spell
    ":highlight SpellBad gui=underline guibg=NONE guifg=red
    :syn match TmlDoubleWords /\c\<\(\S\+\)\_s\+\1\ze\_s/ 
    :highlight TmlDoubleWords gui=underline guibg=NONE guifg=red
else
    "colorscheme moria, twilight, solarized, inkpot, corporation, monokai,
    colorscheme jellybeans
    set guifont=Monaco\ 14
    "set guifont=Droid\ Sans\ Mono\ 14
endif

"let g:fullscreen = 1
:au BufRead *.tex set spell
:highlight SpellBad gui=underline guibg=NONE guifg=red
if matchstr(expand("%"),".*\.tex") != ""
"if matchstr(expand("%"),"manuscript\.tex$") != ""
    :iab teh the
    :iab aa amino-acid
    :iab hfl hydrophilic
    :iab hfb hydrophobic
    :iab amf amphiphilic
    :iab ss secondary structure
    :iab sc sidechain
    :iab bb backbone
    :iab com1 center of mass
    :iab bs beta-sheet
    :iab rc random-coil
    :iab ah $\alpha$-helix
    :iab hh half-helix
    :iab ahc $\alpha$-helical
    :iab 1bw bulk water
    :iab 1int air/water interface
    :iab 1pmf potential of mean force
    :iab pp peptide
    :iab 1leu leucine
    :iab 1lys lysine
    :iab KL LK$\alpha$14
    :iab ie i.e.
    :iab adn and
    :iab ii3 \emph{CN$_i$-CN$_{i+3}$}
    :iab ca1 C$_{\alpha}$
    :iab cb1 C$_{\beta}$
    :iab cgn \emph{cg-neutral}
    :iab cgc \emph{cg-charged}
    :iab DH Debye-H\"uckel
    ":map <F2> viWB<ESC><ESC>i\emph{<ESC>Ea}<ESC>
endif

map <silent> <F11>
\    :call system("wmctrl -ir " . v:windowid . " -b toggle,fullscreen")<CR>

set antialias
"set guicursor+=a:blinkon0    " disable cursor blink
"set guioptions-=r   "kill right scrollbar
"set guioptions-=l   "kill left scrollbar
"set guioptions-=L   "kill left scrollbar multiple buffers
"set guioptions-=T   "kill toolbar
