let mysyntaxfile = "~/.vim/syntax/mysyntax.vim"
:syntax on
"augroup syntax
":autocmd FileType *      set formatoptions=tcql nocindent comments&
":autocmd FileType c,cpp  set formatoptions=croql cindent comments=sr:/*,mb:*,ex:*/,://
":autocmd FileType mdp.gromacs set omnifunc=mdpcomplete#Complete
"" imap <C-n> <C-x><C-o>
":autocmd FileType python set omnifunc=pythoncomplete#Complete
":autocmd BufWritePre *.gro call Update_number_of_atoms()
":au BufNewFile,BufRead *.rtp    setf top.gromacs
":au BufNewFile,BufRead *.gp  set filetype=gnuplot
":au BufNewFile,BufRead *.comms  set filetype=sh
":au BufNewFile,BufRead .vmdrc  set filetype=tcl
":au BufNewFile,BufRead bash-fc-*    set syntax=sh
":au BufNewFile,BufReadPost *.lmp           setfiletype lammps
":au BufNewFile,BufReadPost *.lammps           setfiletype lammps
":au BufNewFile,BufReadPost system.in.init           setfiletype lammps
":au BufNewFile,BufReadPost system.in.settings           setfiletype lammps
":au BufNewFile,BufReadPost run.in.*           setfiletype lammps
":au BufNewFile,BufReadPost in.*           setfiletype lammps
"augroup end

augroup pencil
  autocmd!
  autocmd FileType markdown,mkd call pencil#init()
  autocmd FileType text         call pencil#init()
  "autocmd FileType tex,latex         call pencil#init()
augroup END

highlight Search cterm=NONE ctermfg=black ctermbg=yellow
":highlight SpellBad gui=underline guibg=NONE guifg=NONE
":au BufRead *.tex set spell

:map <F6> {v}!par -w70<CR>
:vmap <F6> !par -w70<CR>
":map <F4> :highlight Normal ctermfg=black ctermbg=white<CR>
:map <F4> :set background=light<CR>:colorscheme earendel<CR>

":set autoindent
set autowrite
set ruler
:ab #i #include
:ab #b /********************************************************
:ab #c ###################################################################
:ab #d %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
:ab #e ********************************************************/
:ab #l /*------------------------------------------------------*/
:set sw=4
set notextmode
set notextauto
set hlsearch
set incsearch
set history=1000
set undolevels=1000
":set textwidth=100
set ignorecase          " ignore case when searching
set smartcase           " no ignorecase if Uppercase char present

map <F8> :w <enter> :!/home/cdalgicdir/soft/bin/vimrun % <enter>
map <F2> :w <enter> :!/home/cdalgicdir/soft/bin/latexcrop % <enter>
"nnoremap    <F2> :<C-U>setlocal lcs=tab:>-,trail:-,eol:$ list! list? <CR>

" LATEX PLUGIN options 

" REQUIRED. This makes vim invoke Latex-Suite when you open a tex file.
"filetype plugin on

" IMPORTANT: grep will sometimes skip displaying the file name if you
" search in a singe file. This will confuse Latex-Suite. Set your grep
" program to always generate a file-name.
set grepprg=grep\ -nH\ $*

" OPTIONAL: This enables automatic indentation as you type.
"filetype indent on

" OPTIONAL: Starting with Vim 7, the filetype of empty .tex files defaults to
" 'plaintex' instead of 'tex', which results in vim-latex not being loaded.
" The following changes the default filetype back to 'tex':
let g:tex_flavor='latex'
"
" Use spaces instead of tabs for python
"set tabstop=4
"set shiftwidth=4
"set expandtab
"retab

" Bubble single lines
nmap <C-Up> ddkP
nmap <C-Down> ddp
" " Bubble multiple lines
vmap <C-Up> xkP`[V`]
vmap <C-Down> xp`[V`]
" Visually select the text that was last edited/pasted
map gV `[v`]
nore ; :
nore , ;
" nnoremap <Up> gk
"let g:Tex_CompileRule_pdf = 'pdflatex -synctex=1 -src-specials -interaction=nonstopmode $*'
"let g:Tex_ViewRule_pdf = 'okular --unique'
"function! SyncTexForward()
"    let s:syncfile = fnamemodify(fnameescape(Tex_GetMainFileName()), ":r").".pdf"
"    let execstr = "silent !okular --unique ".s:syncfile."\\#src:".line(".").expand("%\:p").' &'
"    exec execstr
"endfunction
"nnoremap <Leader>f :call SyncTexForward()<CR>
"
:set nocompatible
:filetype off
" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'

" The following are examples of different formats supported.
" Keep Plugin commands between vundle#begin/end.
" plugin on GitHub repo
"Plugin 'tpope/vim-fugitive'
" plugin from http://vim-scripts.org/vim/scripts.html
"Plugin 'L9'
Plugin 'tpope/vim-surround'
Plugin 'tpope/vim-repeat'
Plugin 'tpope/vim-commentary'
Plugin 'matchit.zip'
Plugin 'Lokaltog/vim-easymotion'
Plugin 'kien/rainbow_parentheses.vim'
Plugin 'beloglazov/vim-online-thesaurus'
Plugin 'HubLot/vim-gromacs'
" colorschemes
Plugin 'flazz/vim-colorschemes'
Plugin 'depuracao/vim-darkdevel'
Plugin 'altercation/solarized'
Plugin 'github-theme'
" Markdown syntax highlighting
Plugin 'godlygeek/tabular'
Plugin 'plasticboy/vim-markdown'
Plugin 'bling/vim-airline'
Plugin 'benmills/vimux'
Plugin 'kien/ctrlp.vim'
Plugin 'jeetsukumaran/vim-buffergator'
Plugin 'vim-scripts/earendel'
Plugin 'mayansmoke'
Plugin 'junegunn/goyo.vim'
Plugin 'mtth/scratch.vim'
Plugin 'aquach/vim-mediawiki-editor'
Plugin 'chikamichi/mediawiki.vim'
Plugin 'junegunn/limelight.vim'
Plugin 'reedes/vim-pencil'
Plugin 'reedes/vim-thematic'
Plugin 'reedes/vim-colors-pencil'
Plugin 'nickburlett/vim-colors-stylus'
Plugin 'scrooloose/nerdcommenter'
Plugin 'scrooloose/nerdtree'
Plugin 'vimoutliner/vimoutliner'
"Plugin 'Txtfmt-The-Vim-Highlighter'
"Plugin 'reedes/vim-textobj-sentence'
" Git plugin not hosted on GitHub
"Plugin 'https://github.com/Lokaltog/vim-easymotion.git'
"Plugin 'https://github.com/vim-scripts/Rainbow-Parenthsis-Bundle.git'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line
:let g:notes_directory = '~/Documents/Notes'

autocmd FileType top.gromacs set commentstring=;\ %s
autocmd FileType mdp.gromacs set commentstring=;\ %s

" Toggle fold state between closed and opened. 
  " 
  " If there is no fold at current line, just moves forward. 
  " If it is present, reverse it's state. 
  fun! ToggleFold() 
  if foldlevel('.') == 0 
  normal! l 
  else 
  if foldclosed('.') < 0 
  . foldclose 
  else 
  . foldopen 
  endif 
  endif 
  " Clear status line 
  echo 
  endfun 
  " Map this function to Space key. 
  noremap <space> :call ToggleFold()<CR>

" Rainbowparentheses always on
au VimEnter * RainbowParenthesesToggle
au Syntax * RainbowParenthesesLoadRound
au Syntax * RainbowParenthesesLoadSquare
au Syntax * RainbowParenthesesLoadBraces
let g:rbpt_colorpairs = [
    \ ['brown',       'RoyalBlue3'],
    \ ['Darkblue',    'SeaGreen3'],
    \ ['darkgray',    'DarkOrchid3'],
    \ ['darkgreen',   'firebrick3'],
    \ ['darkcyan',    'RoyalBlue3'],
    \ ['darkred',     'SeaGreen3'],
    \ ['darkmagenta', 'DarkOrchid3'],
    \ ['brown',       'firebrick3'],
    \ ['gray',        'RoyalBlue3'],
    \ ['black',       'SeaGreen3'],
    \ ['darkmagenta', 'DarkOrchid3'],
    \ ['Darkblue',    'firebrick3'],
    \ ['darkgreen',   'RoyalBlue3'],
    \ ['darkcyan',    'SeaGreen3'],
    \ ['darkred',     'DarkOrchid3'],
    \ ['red',         'firebrick3'],
    \ ]
let g:rbpt_max = 16
let g:rbpt_loadcmd_toggle = 0

" matchit
":source ~/.vim/bundle/vim-matchit/plugin/matchit.vim

" CtrlP
let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlP'
let g:ctrlp_working_path_mode = 'c'
let g:ctrlp_custom_ignore = {
  \ 'dir':  '\v[\/](\.(git|hg|svn)|\_site)$',
  \ 'file': '\v\.(exe|so|dll|class|png|jpg|jpeg|xtc|edr|cpt|tpr|pdf)$',
  \}
" https://joshldavis.com/2014/04/05/vim-tab-madness-buffers-vs-tabs/
" Use a leader instead of the actual named binding
nmap <leader>p :CtrlP<cr>

" Easy bindings for its various modes
nmap <leader>bb :CtrlPBuffer<cr>
nmap <leader>bm :CtrlPMixed<cr>
nmap <leader>bs :CtrlPMRU<cr>
" /CtrlP

set wildignore=*.log,*.aux,*.dvi,*.aut,*.aux,*.bbl,*.blg,*.dvi,*.fff,*.log,*.out,*.pdf,*.ps,*.toc,*.ttt
set thesaurus+=~/.vim/thesaurus/mthesaur.txt
set dictionary+=/usr/share/dict/words

" Buffergator
" Use the right side of the screen
let g:buffergator_viewport_split_policy = 'R'

" I want my own keymappings...
let g:buffergator_suppress_keymaps = 0

" Looper buffers
"let g:buffergator_mru_cycle_loop = 1

" Go to the previous buffer open
nmap <leader>jj :BuffergatorMruCyclePrev<cr>

" Go to the next buffer open
nmap <leader>kk :BuffergatorMruCycleNext<cr>

" View the entire list of buffers open
nmap <leader>bl :BuffergatorOpen<cr>

" Shared bindings from Solution #1 from earlier
nmap <leader>T :enew<cr>
nmap <leader>bq :bp <BAR> bd #<cr>

" /Buffergator

":command! -nargs=1 -range SuperRetab <line1>,<line2>s/\v%(^ *)@<= {<args>}/\t/g
"
"func! WordProcessorMode() 
"  setlocal formatoptions=1 
"  setlocal noexpandtab 
"  map j gj 
"  map k gk
"  setlocal spell spelllang=en_us 
"  set complete+=s
"  set formatprg=par
"  setlocal wrap 
"  setlocal linebreak 
"endfu 
"com! WP call WordProcessorMode()
let g:Tex_DefaultTargetFormat = 'pdf'
let g:Tex_MultipleCompileFormats = 'pdf'
let g:Tex_CompileRule_pdf = 'pdflatex -interaction=nonstopmode $*'
let g:Tex_GotoError = 0
let g:Tex_ViewRule_pdf = 'evince'
" Initial fold level for markdown syntax plugin
let g:vim_markdown_initial_foldlevel=4
" Highlight YAML frontmatter
let g:vim_markdown_frontmatter=1
let g:vim_markdown_math=1
" Highlight line with \l, 'l to return to line and :match to clear
nnoremap <silent> <Leader>l ml:execute 'match Search /\%'.line('.').'l/'<CR>

" vim-airline settings
"let g:airline_left_sep=''
"let g:airline_right_sep=''
let g:airline#extensions#whitespace#trailing_format = 'trailing[%s]'
let g:airline#extensions#whitespace#mixed_indent_format = 'mixed-indent[%s]'
let g:airline#extensions#branch#enabled = 1
let g:airline#extensions#branch#empty_message = ''
" Enable the list of buffers
let g:airline#extensions#tabline#enabled = 1
" Hide function display (don't use it)
let g:airline#extensions#tagbar#enabled = 0

" Show just the filename
let g:airline#extensions#tabline#fnamemod = ':t'
let g:airline_powerline_fonts=1

if !exists('g:airline_symbols')
   let g:airline_symbols = {}
endif

" unicode symbols
let g:airline_left_sep = '»'
let g:airline_left_sep = '▶'
let g:airline_right_sep = '«'
let g:airline_right_sep = '◀'
let g:airline_symbols.linenr = '␊'
let g:airline_symbols.linenr = '␤'
let g:airline_symbols.linenr = '¶'
let g:airline_symbols.branch = '⎇'
let g:airline_symbols.paste = 'ρ'
let g:airline_symbols.paste = 'Þ'
let g:airline_symbols.paste = '∥'
let g:airline_symbols.whitespace = 'Ξ'

let g:airline_theme='dark'

" Vimux settings
let g:VimuxHeight = "30"
let g:VimuxOrientation = "v"
let g:VimuxUseNearestPane = 0

" Vimux Mappings
nmap <leader>vp :VimuxPromptCommand<cr>
nmap <leader>vl :VimuxRunLastCommand<cr>
nmap <leader>vq :VimuxCloseRunner<cr>
nmap <leader>vx :VimuxInterruptRunner<cr>

" Wikimedia
let g:mediawiki_editor_url = "localhost/mediawiki"
"let g:mediawiki_editor_path = ""
let g:mediawiki_editor_username = "cdalgicdir"
"g:mediawiki_editor_password

" Limelight
" Color name (:help cterm-colors) or ANSI code
"let g:limelight_conceal_ctermfg = 'gray'
"let g:limelight_conceal_ctermfg = 240
let g:limelight_conceal_ctermfg = (&bg == 'dark') ? 'red' : 'gray'
"let g:limelight_conceal_ctermfg = 245  " Solarized Base1
"let g:limelight_conceal_guifg = '#8a8a8a'  " Solarized Base1

" Color name (:help gui-colors) or RGB color
"let g:limelight_conceal_guifg = 'DarkGray'
"let g:limelight_conceal_guifg = '#777777'
let g:limelight_conceal_guifg = (&bg == 'dark') ? 'red' : 'gray'

" Default: 0.5
let g:limelight_default_coefficient = 0.7

" Number of preceding/following paragraphs to include (default: 0)
let g:limelight_paragraph_span = 0

" Beginning/end of paragraph
"   When there's no empty line between the paragraphs
"   and each paragraph starts with indentation
let g:limelight_bop = '^\s'
let g:limelight_eop = '\ze\n^\s'

" Highlighting priority (default: 10)
"   Set it to -1 not to overrule hlsearch
let g:limelight_priority = -1

let g:pencil#autoformat = 0
noremap <buffer> <silent> <F7> :<C-u>PFormatToggle<cr>
inoremap <buffer> <silent> <F7> <C-o>:PFormatToggle<cr>
let g:pencil#textwidth = 74
let g:pencil#cursorwrap = 1     " 0=disable, 1=enable (def)
set statusline=%<%f\ %h%m%r%w\ \ %{PencilMode()}\ %=\ col\ %c%V\ \ line\ %l\,%L\ %P
set rulerformat=%-12.(%l,%c%V%)%{PencilMode()}\ %P
let g:airline_section_x = '%{PencilMode()}'

let g:pencil#mode_indicators = {'hard': '␍', 'auto': 'ª', 'soft': '⤸', 'off': '',}



" Highlight words to avoid in tech writing
" =======================================
"
"   obviously, basically, simply, of course, clearly,
"   just, everyone knows, However, So, easy

"   http://css-tricks.com/words-avoid-educational-writing/

highlight TechWordsToAvoid ctermbg=red ctermfg=white
match TechWordsToAvoid /\cobviously\|basically\|simply\|of\scourse\|clearly\|just\|everyone\sknows\|however\|so,\|easy/
autocmd BufWinEnter * match TechWordsToAvoid /\cobviously\|basically\|simply\|of\scourse\|clearly\|just\|everyone\sknows\|however,\|so,\|easy/
autocmd InsertEnter * match TechWordsToAvoid /\cobviously\|basically\|simply\|of\scourse\|clearly\|just\|everyone\sknows\|however,\|so,\|easy/
autocmd InsertLeave * match TechWordsToAvoid /\cobviously\|basically\|simply\|of\scourse\|clearly\|just\|everyone\sknows\|however,\|so,\|easy/
autocmd BufWinLeave * call clearmatches()

map <C-n> :NERDTreeToggle<CR>
let g:pencil_higher_contrast_ui = 0   " 0=low (def), 1=high
let g:pencil_neutral_headings = 1   " 0=blue (def), 1=normal
let g:pencil_neutral_code_bg = 1   " 0=gray (def), 1=normal
let g:pencil_spell_undercurl = 1       " 0=underline, 1=undercurl (def)
let g:pencil_terminal_italics = 1
"let g:airline_theme = 'pencil'

let g:thematic#themes = {
\ 'bubblegum'  : {
\                },
\ 'jellybeans' : { 'laststatus': 0,
\                  'ruler': 1,
\                },
\ 'pencil_dark' :{'colorscheme': 'pencil',
\                 'background': 'dark',
\                 'airline-theme': 'pencil',
\                 'ruler': 1,
\                },
\ 'pencil_lite' :{'colorscheme': 'pencil',
\                 'background': 'light',
\                 'airline-theme': 'pencil',
\                 'ruler': 1,
\                },
\ 'write'   : { 'colorscheme': 'pencil',
\                  'background': 'light',
\                  'columns': 75,
\                  'font-size': 17,
\                  'fullscreen': 1,
\                  'laststatus': 0,
\                  'linespace': 8,
\                  'typeface': 'Courier Prime',
\                },
\ }

function! s:goyo_enter()
  if has('gui_running')
    set fullscreen
    colorscheme pencil
    set guifont=Courier\ Prime\ 17
    set background=light
    set linespace=7
  elseif exists('$TMUX')
    silent !tmux set status off
    silent !tmux list-panes -F '\#F' | grep -q Z || tmux resize-pane -Z
  endif
  set noshowmode
  set noshowcmd
  set scrolloff=999
  set antialias
  set guicursor+=a:blinkon0    " disable cursor blink
  set guioptions-=r   "kill right scrollbar
  set guioptions-=l   "kill left scrollbar
  set guioptions-=L   "kill left scrollbar multiple buffers
  set guioptions-=T   "kill toolbar
  Limelight
  let b:quitting = 0
  let b:quitting_bang = 0
  autocmd QuitPre <buffer> let b:quitting = 1
  cabbrev <buffer> q! let b:quitting_bang = 1 <bar> q!
  " ...
endfunction

function! s:goyo_leave()
  if has('gui_running')
    set nofullscreen
    set background=dark
    set linespace=0
  elseif exists('$TMUX')
    silent !tmux set status on
    silent !tmux list-panes -F '\#F' | grep -q Z && tmux resize-pane -Z
  endif
  set showmode
  set showcmd
  set scrolloff=5
  set guioptions+=r   "kill right scrollbar
  Limelight!
  " Quit Vim if this is the only remaining buffer
  if b:quitting && len(filter(range(1, bufnr('$')), 'buflisted(v:val)')) == 1
    if b:quitting_bang
      qa!
    else
      qa
    endif
  endif
  " ...
endfunction

autocmd! User GoyoEnter nested call <SID>goyo_enter()
autocmd! User GoyoLeave nested call <SID>goyo_leave()

let g:goyo_height=50
let g:goyo_width=75

"noremap <silent> <F5> :<C-u>ThematicNarrow<cr>
"noremap <silent> <F6> :<C-u>ThematicWiden<cr>
"inoremap <silent> <F5> <C-o>:ThematicNarrow<cr>
"inoremap <silent> <F6> <C-o>:ThematicWiden<cr>

function! WC()
    echo "\n"
    let filename = expand("%")
    let cmd = "~/Downloads/texcount/texcount.pl " . filename . ""
    let result = system(cmd)
    echo result . ""
endfunction

command WC call WC()
