# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
#ZSH_THEME="robbyrussell"
#ZSH_THEME="pure"
#ZSH_THEME="purem"
ZSH_THEME="cobalt2m"
#ZSH_THEME="powerlevel9k/powerlevel9k"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git bundler tmux)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
autoload -U zmv
alias mmv='noglob zmv -W'

autoload bashcompinit
bashcompinit

complete -f -X '!*.pdf' mupdf
complete -f -X '!*.@(pdf|djvu|ps)' zathura
complete -f -X '!*.pdf' pdfviewer
complete -f -X '!*.corr' ramaplot
complete -f -X '!*.gp' gp
complete -f -X '!*.gp' gpp
complete -f -X '!*.pdf' cn



cd() {
   builtin cd "$@"
   [[ $PWD == "$HOME/Downloads" ]] && ls -tr || ls
}

function pawk {
    local first="awk '{ if ( \$1 !~ /^[@|#]/) print "
    local last="}'"
    local cmd="${first}\$${1}${last}"
    eval $cmd
}

function dirawk {
    local cmd="awk '{split(\$1,a,\"/\");print a[1]}'"
    eval $cmd
}

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

alias emerillon='export CLUTTER_VBLANK=none && emerillon'
export SVNROOT=svn+ichiport://cdalgicdir@88.255.97.68/home/svnroot

# added by Anaconda2 4.2.0 installer
export PATH="/home/cdalgicdir/anaconda2/bin:$PATH"
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib64
export PATH=$PATH:/usr/local/cuda/bin

alias alert_helper='history|tail -n1|sed -e "s/^\s*[0-9]\+\s*//" -e "s/;\s*alert$//"'
alias alert='notify-send -i /usr/share/icons/gnome/32x32/apps/gnome-terminal.png "[$?] $(alert_helper)"'
export LC_TIME=en_GB.utf8

# add /home/soft software
#GROMACS="/home/soft/gromacs/gromacs-4.6.7/inst/shared"
SOFT=$HOME/soft
TMUX=$SOFT/tmux/tmux-2.3
GNUPLOT=$SOFT/gnuplot/gnuplot-5.0.5-qt5
GROMACS=$SOFT/gromacs/gromacs-4.6.7
PLUMED=$SOFT/plumed/plumed-2.2.4
#VOTCA=$SOFT/votca/votca-1.2.4-fixed
#VOTCA=$SOFT/votca/votca-1.3
VIM=$SOFT/vim/vim
MUPDF=$SOFT/mupdf/mupdf
export LD_LIBRARY_PATH=$MUPDF/lib:$LD_LIBRARY_PATH
export PATH=$VIM/bin:$PATH
export PATH=/home/cdalgicdir/anaconda/bin:$PATH
export PATH=$TMUX/bin:$SOFT/bin:$PATH
export PATH=$GNUPLOT/bin:$PATH
#export PATH=$TMUX/bin:$GNUPLOT/bin:$SOFT/bin:$PATH
source $GROMACS/bin/GMXRC.bash
export GMXLIB=$GROMACS/share/gromacs/top
#source $VOTCA/bin/VOTCARC.bash
export PATH=$PATH:$PLUMED/bin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PLUMED/lib
export PLUMED_KERNEL=$PLUMED/lib/libplumedKernel.so
export PATH=$PATH:$HOME/soft/moltemplate/moltemplate/src
export MOLTEMPLATE_PATH=$HOME/soft/moltemplate/moltemplate/common
export PATH=$PATH:$HOME/soft/espressopp/espressopp/bin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/soft/espressopp/espressopp/lib
export PYTHONPATH=$PYTHONPATH:$HOME/soft/espressopp/espressopp/lib/python2.7/dist-packages
#export PATH=$HOME/progs/screen-4.2.1/bin:$PATH
alias diff-side-by-side='diff --side-by-side -W"`tput cols`"'
alias diff-side-by-side-changes='diff --side-by-side --suppress-common-lines -W"`tput cols`"'
#[ -r /home/cdalgicdir/.byobu/prompt ] && . /home/cdalgicdir/.byobu/prompt   #byobu-prompt#
#CDPATH=$CDPATH:~/remote
# get airline working 
export TERM=xterm-256color
#export TERM=screen-256color-bce
#export TERM=screen-256color
#so as not to be disturbed by Ctrl-S ctrl-Q in terminals:
stty -ixon

if [ -f ~/.bash_aliases_soft ]; then
    . ~/.bash_aliases_soft
fi

export PATH=$PATH:$SOFT/wham/bin
export LC_NUMERIC="en_US.UTF-8"
export PROMPT_COMMAND="history -a"
export PATH=$PATH:$HOME/.local/bin
export LESS='-R'
export LESSOPEN='|~/.lessfilter %s'
export PLUMED_VIMPATH=$PLUMED/lib/plumed/vim
#export SSH_AUTH_SOCK=$HOME/.gnupg/S.gpg-agent.ssh

unset HISTSIZE
unset HISTFILESIZE
HISTIGNORE="&:ls:[bf]g:exit:..:l:dow"
HOSTNAME="$(hostname)"
HOSTNAME_SHORT="${HOSTNAME%%.*}"
HISTFILE="${HOME}/.history/$(date -u +%Y/%m/%d.%H.%M.%S)_${HOSTNAME_SHORT}_$$"
mkdir -p "$(dirname "$HISTFILE")"
histgrep () {
    grep --color=auto -r "$@" $(ls -dv ~/.history)
    history | grep --color=auto "$@"
}
