#! /bin/bash

help () {
    echo -e "Usage: gpp file [option]
Options: 
    -lw n : linewidth n [default 3]
    -fs n : fontsize n [default 16]
    -l [x,y]: set output size x,y [default: 8,4]
    -size x,y: set output size x,y [default: 1500,1000]
    -e : enhanced 
    -png : use pngcairo terminal
    -dashed : dashed
    -dl : dash-length
    -h : print help
	"
}

option=""
linewidth=1.5
length="8,4"
fontsize=16
fonttype="Gill Sans"
term="pdfcairo"
size="1500,1000"
show=true

if [[ $# -ge 1 ]] ; then
    if [[ $1 != -* ]]; then
        file="$1"
        shift
    fi
    while [[ $# -ge 1 ]]
    do
        case $1 in

            -e)
                option="${option} enhanced"
                shift ;;

	    -l)
		if [[ -z $2 ]]; then
		    option="${option} size $length"
		    shift
		else
		    if [[ $2 != -* ]]; then
			option="${option} size $2"
			shift 2
		    else
			option="${option} size $length"
			shift
		    fi
		fi
		    ;;

	    -dashed|-d)
		option="${option} dashed"
		shift ;;

	    -dashlength|-dl)
		option="${option} dashlength $2"
		shift 2;;

	    -lw)
		linewidth=$2
		shift 2;;

	    -fs | -fontsize)
		fontsize=$2
		shift 2;;

	    -size)
		size=$2
		shift 2;;

	    -png)
		term="pngcairo"
		#fontsize=32
		linewidth=1
		fontsize=20
		size="1000,600"
		option="$option crop"
		shift ;;

	    -noshow | -no | -n)
		show=false
		shift ;;

	    -h|-help)
		help
		exit 0
		;;

	    *)
		echo "Unknown option $1"
		help
		exit 1
	esac
    done
fi

font="\"$fonttype, $fontsize\""

if [[ $term == "pdfcairo" ]]; then
    terminal="$term font $font linewidth $linewidth rounded $option"
    output=${file%.gp}.pdf
    app="mupdf-x11"
elif [[ $term == "pngcairo" ]]; then
    terminal="$term font $font linewidth $linewidth size $size $option"
    output=${file%.gp}.png
    app="eog"
else
    echo "Unknown terminal!"
    exit 1
fi

echo "$output created!"

gnuplot "${file}" -e "set terminal ${terminal};set output \"${output}\";rep;set output"
$show && $app $output &
