#! /bin/bash

help () {
    echo -e "Usage: gpp file [option]
Options: 
    -lw n : linewidth n [default 3]
    -fs n : fontsize n [default 16]
    -ft string : font fontname [default Gill Sans]
    -l [x,y]: set output size x,y [default: 8,4]
    -size x,y: set output size x,y [default: 1500,1000]
    -e : enhanced 
    -png : use pngcairo terminal
    -dashed : dashed
    -dl : dash-length
    -h : print help
	"
}

option=""
linewidth=3
length="8,4"
#fontsize=16
#fonttype="Gill Sans"
#fonttype="Rosario"
#fonttype="Actor"
fontsize=22
fonttype="Linotte-Regular"
#fonttype="Ubuntu"
#fonttype="Comfortaa"
term="pdfcairo"
size="1500,1000"
show=true
usersetlw=false
extra=""

if [[ $# -ge 1 ]] ; then
    if [[ $1 != -* ]]; then
        file="$1"
        shift
    fi
    while [[ $# -ge 1 ]]
    do
        case $1 in

            -e | -enhanced)
                option="${option} enhanced"
                shift ;;

	    -l | -length)
		if [[ -z $2 ]]; then
		    option="${option} size $length"
		    shift
		else
		    if [[ $2 != -* ]]; then
			option="${option} size $2"
			shift 2
		    else
			option="${option} size $length"
			shift
		    fi
		fi
		    ;;

	    -d | -dashed)
		option="${option} dashed"
		shift ;;

	    -dl | -dashlength)
		option="${option} dashlength $2"
		shift 2;;

	    -lw | -linewidth)
		linewidth=$2 && usersetlw=true
		shift 2;;

	    -fs | -fontsize)
		fontsize=$2
		shift 2;;

	    -ft | -fonttype)
		fonttype=$2
		shift 2;;

	    -size)
		size=$2
		shift 2;;

	    -ps | -pointsize)
		pointsize=$2
		extra="set pointsize $pointsize"
		shift 2;;

	    -png)
		term="pngcairo"
		#fontsize=32
		$usersetlw || linewidth=2
		fontsize=20
		size="1000,600"
		option="$option crop"
		shift ;;

	    -noshow | -no | -n)
		show=false
		shift ;;

	    -h|-help)
		help
		exit 0
		;;

	    *)
		echo "Unknown option $1"
		help
		exit 1
	esac
    done
fi

font="\"$fonttype, $fontsize\""

if [[ $term == "pdfcairo" ]]; then
    terminal="$term font $font linewidth $linewidth rounded $option"
    output=${file%.gp}.pdf
    #ftt=$(echo ${fonttype} | sed 's/ //g')
    output=${file%.gp}.pdf
    app="mupdf"
elif [[ $term == "pngcairo" ]]; then
    terminal="$term font $font linewidth $linewidth size $size $option"
    output=${file%.gp}.png
    app="eog"
else
    echo "Unknown terminal!"
    exit 1
fi

echo "$output created!"

gnuplot "${file}" -e "${extra};set terminal ${terminal};set output \"${output}\";rep;set output"
$show && $app $output &
