#! /bin/bash

SIZE="500,1000"
PAUSE_PLOT=2
PAUSE_CALC=10

echo "Calculating energy, temperature and pressure..."

echo -e "Potential\nKinetic\nTotal" | g_energy -o tot-energy.xvg &> /dev/null
echo -e "Temperature" | g_energy -o temperature.xvg &> /dev/null
echo -e "Pressure" | g_energy -o pressure.xvg &> /dev/null

rm /tmp/sil.dat #/tmp/sil2.dat /tmp/sil3.dat

cat << EOF > /tmp/sil.dat &
set term wxt noraise size $SIZE
set multiplot layout 5,1
set key right center
set title "Energy"
p 'tot-energy.xvg' u 1:2 t 'Potential','' u 1:3 t 'Kinetic','' u 1:4 t 'Total'
#set title "Potential Energy"
stats 'tot-energy.xvg' u 2
set title sprintf("Potential Energy=%d kJ/mol",STATS_mean)
#p 'tot-energy.xvg' u 1:2 not 
p 'tot-energy.xvg' u 1:2 not,STATS_mean w d lt -1 not
#set title "Kinetic Energy"
stats 'tot-energy.xvg' u 3
set title sprintf("Kinetic Energy=%d kJ/mol",STATS_mean)
p 'tot-energy.xvg' u 1:3 not,STATS_mean w d lt -1 not
#p 'tot-energy.xvg' u 1:3 not 
#set title "Temperature"
stats 'temperature.xvg' u 2
set title sprintf("Temperature=%.2f K",STATS_mean)
p 'temperature.xvg' u 1:2 not,STATS_mean w d lt -1 not
#set title "Pressure"
stats 'pressure.xvg' u 2
set title sprintf("Pressure=%.2f bar",STATS_mean)
p 'pressure.xvg' u 1:2 not,STATS_mean w d lt -1 not
unset multiplot
pause $PAUSE_PLOT
reread
EOF

#cat << EOF > /tmp/sil.dat &
##set term wxt noraise size $SIZE font "Arial,12"
#set term x11 noraise size $SIZE position 0,0
#set key right center
#p 'tot-energy.xvg' u 1:2 t 'Potential','' u 1:3 t 'Kinetic','' u 1:4 t 'Total'
#pause $PAUSE_PLOT
#reread
#EOF
#
#cat << EOF > /tmp/sil2.dat &
##set term wxt noraise size 600,200 font "Arial,12"
#set term x11 noraise size $SIZE position 0,265
#set key right top
#p 'temperature.xvg' u 1:2 t 'Temperature'
#pause $PAUSE_PLOT
#reread
#EOF
#
#cat << EOF > /tmp/sil3.dat &
##set term wxt noraise size 600,200 font "Arial,12"
#set term x11 noraise size $SIZE position 0,505
#set key right top
#p 'pressure.xvg' u 1:2 t 'Pressure'
#pause $PAUSE_PLOT
#reread
#EOF

while [[ ! -e "tot-energy.xvg" ]] || [[ ! -e "temperature.xvg" ]] || [[ ! -e "pressure.xvg" ]]; do
    sleep 1
done

echo "Calculations done. Plotting..."

gnuplot /tmp/sil.dat &
#sleep 1
#wmctrl -r "Gnuplot" -e 0,0,0,$SIZE
#gnuplot /tmp/sil2.dat &
#gnuplot /tmp/sil3.dat &

while true;do
    echo -e "Potential\nKinetic\nTotal" | g_energy -o tot-energy2.xvg &> /dev/null
    echo -e "Temperature" | g_energy -o temperature2.xvg &> /dev/null
    echo -e "Pressure" | g_energy -o pressure2.xvg &> /dev/null
    mv tot-energy.xvg sil && mv tot-energy2.xvg tot-energy.xvg
    mv temperature.xvg sil && mv temperature2.xvg temperature.xvg
    mv pressure.xvg sil && mv pressure2.xvg pressure.xvg
    rm sil
    rm \#tot-energy.xvg* \#temperature.xvg* \#pressure.xvg* 2>/dev/null
    sleep $PAUSE_CALC
done

rm /tmp/sil.dat /tmp/sil2.dat /tmp/sil3.dat

#cat << EOF > /tmp/sil.dat &
#set term wxt 0 noraise
#set key right center
#p 'energy.xvg' u 1:2 t 'Potential','' u 1:3 t 'Kinetic','' u 1:4 t 'Total'
#pause 1
#reread
#set term wxt 1 noraise
#set key right top
#p 'temperature.xvg' u 1:2 t 'Temperature'
#pause 1
#reread
#set term wxt 2 noraise
#set key right top
#p 'pressure.xvg' u 1:2 t 'Pressure'
#pause 1
#reread
#EOF

