#! /bin/bash

sitedir="$HOME/Dropbox/github/notes/_posts"

#[[ ! -n "$1" ]] && echo "Missing argument!" && exit 1
[[ ! -n "$1" ]] && title="notes" || title="$1"

date=`date +%Y-%m-%d`
fname="$date-${title}.md"

if [[ ! -e "$(eval echo $sitedir/$fname)" ]]; then
    eval cd $sitedir

    echo -e "---\n\
layout: post\n\
tag: ${title}\n\
category: ${title}\n\
---" > $fname

gvim $fname
else
    eval cd $sitedir
    echo "$fname exists, opening..."
    gvim $fname
fi

