#! /bin/bash

###################################################################
# plot multiple files in gnuplot using bash wildcards
###################################################################

lw=6
lwset=false
pointsize="1"
#linetype="points"
linetype="lines"
#linetype="linespoints"
using=" u 1:2 "
q="'"
potfile="*.pot.*"
tabfile="*table*xvg"
max=30
label=1
keypos=''
plotfiles=''
terminal=''
#terminal='set terminal wxt'
range=[:][:]
userset=false
doshift=0
entcorr=0
kT=2.4777 #for T=298K
#kT=2.4943 #for T=300
sas=false
functions=""
column=2
every=1
colslist=()
noplot=false
convert2ns=false
doentcorr=0
doshift=0

plot () {
    gplot $output -c "${style}" -c "${functions}"  -c "${extra}" -c "$keypos" -c "$terminal" -r $range -- "$plotfiles"
}

printcommands () {
    if $noplottab; then
	#echo "plot $plotfiles" | sed 's/,/,\\\n /g'
	echo -e "${functions[@]}\nplot\\\\\n $plotfiles" | sed 's/,/,\\\n /g'
    else
	echo -e "${functions[@]}\nplot $plotfiles"
    fi
}

help () {
    echo "Usage: $ pla file1 file2 file3"
    echo "       $ pla file*             (sames as above)"
    echo "       $ pla file* 4           (uses 4th column)"
    echo "       $ pla file* u 4         (uses 4th column)"
    echo "       $ pla file* -y 2        (sets max yrange)"
    echo "Needs: gplot script from C. Junghans"
}

die() {
  echo -e "$*" >&2
  exit 1
}

genfunc() {
    n=$1
    p1=" avg(x) = (shift(x), ("
    p2=""
    p3="init(x) = ("
    for i in `seq 1 $((n-1))`; do
	p1=$p1"back$i+"
	[[ $i -gt 1 ]] && p2="back$i = back$((i-1)), "$p2
	p3=$p3"back$i = "
    done
    p1=$p1"back$n)/samples(\$0));"
    p2="shift(x) = (back$n = back$((n-1)),"$p2"back1 = x);"
    p3=$p3"back$n = sum = 0)"
    comm="samples(x) = \$0 > $((n-1)) ? $n : (\$0+1);${p1}${p2}${p3}"
    echo $comm
}

isnumber() {
    printf '%f' "$1" &>/dev/null && echo "$1" || echo "-1";
}

###################################################################
# Check taken from gplot script of C. Junghans
###################################################################

if [ "${1#'['}" != "$1" ]; then
   #check for [??:??] or [??:??]{??:??}
   [ -n "$(echo "$1" | grep -e '^\(\[[-.eE[:digit:]]*:[-.eE[:digit:]]*\]\)\{1,2\}$')" ] ||
     die "Range ('$1') has to be in form [??:??]\<[??:??]\>"
   range=$1
   shift
fi

###################################################################
# End of check
###################################################################


while [[ $# -ge 1 ]]; do
    case $1 in
	u)
	    if [[ "${2}" == *:* ]]; then
		x="${2}"
		xl=(${x//:/ })
		using=' u '"${xl[0]}"':'"${xl[1]}"
		column=${xl[1]}
		colslist+=(${x})
	    else
		using=" u $2 "
		column=$2
		colslist+=($column)
	    fi
	    userset=true
	    #using=" u 1:${2} "
	    shift 2;;

	-n | -nop | -noplot)
	    noplot=true
	    noplottab=false
	    shift 1;;

	-nt | -nopt)
	    noplot=true
	    noplottab=true
	    shift 1;;

	-ns)
	    convert2ns=true
	    shift 1;;

	w)
	    linetype=$2
	    shift 2;;

	ps)
	    pointsize=$2
	    shift 2;;

	lw)
	    lw=$2
	    lwset=true
	    shift 2;;

	ev|every)
	    every=$2
	    shift 2;;

	-y)
	    range="[:][:$2]"
	    shift 2;;

	-nxy)
	    nxy=1
	    shift ;;

	-sas)
	    sas=true
	    linetype="points ps 1"
	    extra="set xlabel \"distance(nm)\";set ylabel \"SASA (nm^2)\";set term wxt enhanced"
	    shift ;;

	not)
	    label=0
	    shift 1;;

	-keyout|-ko)
	    keypos='set key out'
	    shift 1;;

	-keybot|-kb)
	    keypos='set key right bottom'
	    shift 1;;

	-keyleft|-kl)
	    keypos='set key left reverse Left'
	    shift 1;;

	-dihe)
	    range="[-180:180][:]"
	    extra="set xtics 45;set xlabel '{/Symbol f}';set ylabel 'P({/Symbol f})'"
	    shift 1;;

	-dih)
	    range="[-180:180][:]"
	    extra="set xtics 45;set xlabel 'angle';set ylabel 'Probability'"
	    shift 1;;

	-rama)
	    terminal=$terminal' enhanced'
	    range="[-180:180][-180:180]"
	    extra="set xtics 60;set ytics 60;set xlabel '{/Symbol f} (degrees)';set ylabel '{/Symbol y} (degrees)'"
	    shift 1;;

	-dashed|-dash)
	    terminal=$terminal' dashed'
	    shift 1;;

	-pdf)
	    $lwset && lw=$lw || lw=3
	    terminal='set terminal pdfcairo font "Gill Sans,12" linewidth '"$lw"' rounded'
	    output='-o out.pdf'
	    echo "Generating out.pdf"
	    shift 1;;

	-gp)
	    outgp=true
	    gpcomm='save "out.gp"'
	    echo "Generating out.gp"
	    shift 1;;

	-shift)
	    doshift=1
	    keypos='set key right bottom'
	    shift;;

	-entcorr|-ec)
	    doentcorr=1
	    shift;;
	    
	-pmf)
	    doshift=1
	    doentcorr=1
	    keypos='set key right bottom'
	    shift;;

	-movavg|-ma)
	    domovavg=1
	    if [[ $# -gt 1 ]]; then
		[[ `isnumber $2` != -1 ]] && n="$2" && shift || n=5
	    else
		n=10
	    fi
	    shift
	    functions=`genfunc $n`
	    ;;

	-cummean|-cm)
	    docummean=1
	    [[ $functions == "" ]] && functions='sum=0'
	    shift;;

	-mac)
	    docummean=1 && domovavg=1
	     if [[ $# -gt 1 ]]; then
		[[ `isnumber $2` != -1 ]] && n="$2" || n=5
		shift 2
	    else
		n=5
		shift
	    fi
	    functions=`genfunc $n`
	    ;;

	[0-9]|[0-9][0-9])
	    column=$1
	    #using=" u 1:${1} "
	    userset=true
	    colslist+=("1:$column")
	    shift ;;

	-h | -help | --help | --h)
	    help
	    exit 0
	    ;;
	*)
	    filelist=(${filelist[@]} $1)
	    shift ;;

    esac
done

if [[ ${#filelist[@]} == 1 ]] && [[ ! -f ${filelist[0]} ]]; then echo "File not found!" && exit 1;fi

style="do for [i=1:20] { set style line i linewidth $lw }"
ev=" every ${every}"

# shift to zero for PMFs (only works for the second column
if [[ $doshift == 1 ]]; then
    shiftlist=()
    shiftRlist=()
    for f in ${filelist[@]}; do
	shiftR=`tail -1 ${f} | awk '{print $1}'`
	[[ $shiftR == "" ]] && shiftR=`tail -2 ${f} | awk '{print $2}'`
	shift=`tail -1 ${f} | awk '{print $2}'`
	[[ $shift == "" ]] && shift=`tail -2 ${f} | awk '{print $2}'`
	shiftRlist+=("$shiftR")
	shiftlist+=("$shift")
    done
fi

# linetypes
if [ "${linetype}" == "lines" ] || [ "${linetype}" == "l" ] ; then
    with=" with $linetype "
    #with=" with $linetype lw $lw "
elif [ "${linetype}" == "points" ] || [ "${linetype}" == "p" ] || [ "${linetype}" == "linepoints" ] || [ "${linetype}" == "lp" ]; then
    with=" with $linetype ps $pointsize "
elif [[ $linetype == *yer* ]]; then
    using=" u 1:2:3 "
    with=" with $linetype "
else
    with=" with $linetype "
fi

i=0
for file in ${filelist[@]}
do
    $userset || colslist=()
    if [[ -f $file ]]; then
	if [[ $file == $tabfile && $file != *table_d*.xvg && $file != *table_a*.xvg && $file != *table_b*.xvg ]]; then
	    if ! $userset ; then
		colslist+=("1:6")
		#ymax=1.5
		[[ $range == "[:][:]" ]] && range="[:][:5]"
	    fi
	fi
	
	if [[ $nxy == 1 ]]; then
	    NF=`tail -1 ${file} | awk '{print NF}'`
	    for i in `seq 2 $NF`; do
		using=" u 1:$i "
		plotfiles=${plotfiles}${q}${file}${q}${ev}${using}${with}
		if [[ $label == 1 ]]; then
		    #plotfiles=$plotfiles't '$q${i}$q',' 
		    plotfiles=$plotfiles't '$q$((i-1))$q',' 
		else
		    plotfiles=$plotfiles'not,'
		fi
	    done
	elif [[ $sas == true ]]; then
	    plotfiles=${plotfiles}${q}${file}${q}${ev}" using (\$1/1000):2 "${with}" t 'hydrophobic','' ${ev} using (\$1/1000):3 "${with}" t 'hydrophilic','' ${ev} using (\$1/1000):4 "${with}" t 'total',"
	else
	    [[ ${#colslist[@]} -eq 0 ]] && colslist=("1:2")
	    for j in ${colslist[@]}; do
		if [[ "${j}" == *:* ]]; then
		    xl=(${j//:/ })
		    column0=${xl[0]}
		    column=${xl[1]}
		else
		    #using=" u 1:${j} "
		    column=${j}
		fi
		using=" u ${j} "

###################################################################
	    # shift to zero and entropic correction (for second cols only)
	    if [[ $doshift == 1 ]] && [[ $doentcorr == 0 ]]; then
		theshift=${shiftlist[$i]} 
		using=" u $column0:(\$$column-$theshift) "
	    elif [[ $doshift == 0 ]] && [[ $doentcorr == 1 ]]; then
		using=" u $column0:(\$$column+2*$kT*log(\$1)) "
	    elif [[ $doshift == 1 ]] && [[ $doentcorr == 1 ]]; then
		theshift=${shiftlist[$i]} 
		theshiftR=${shiftRlist[$i]} 
		using=" u $column0:(\$$column+2*$kT*(log(\$1/$theshiftR))-$theshift) "
	    fi
###################################################################

	    if $convert2ns; then
		using2=${using:3}
		a=(${using2//:/ })
		[[ ${#a[@]} -gt 1 ]] && using=" u (\$${a[0]}/1000):${a[1]} "
	    fi
		plotfiles=${plotfiles}${q}${file}${q}${ev}${using}${with}
	    if [[ $label == 1 ]]; then
		if [[ ${#colslist[@]} -gt 1 ]]; then
		    titlextra="-${j}"
		else
		    titlextra=""
		fi
		title='t '${q}${file}${titlextra}${q}','
	    else
		title='not,'
	    fi
	    plotfiles=${plotfiles}${title}
	    [[ $domovavg == 1 ]] && plotfiles="${plotfiles}sum = init(0), '' every ::$((n))::-1 using 1:(avg(\$$column)) w l title 'running mean-$n',"
	    [[ $docummean == 1 ]] && plotfiles="${plotfiles}sum=0,'' using 1:(sum = sum + \$$column, sum/(\$0+1)) w l title 'cumulative mean',"
	    done
	fi
	let i=i+1
    fi
done

# remove comma at the end of command
plotfiles=${plotfiles:0:$((${#plotfiles}-1))}

# finally plot all
if $noplot; then
    printcommands
else
    if $outgp; then
	plotfiles="${plotfiles[@]}"";$gpcomm"
    fi
    plot $range $plotfiles
fi

#echo $plotfiles
