#! /bin/bash

sitedir="$HOME/research/_posts"

[[ ! -n "$1" ]] && echo "Missing argument!" && exit 1

date=`date +%Y-%m-%d`
postfile="${date}-${1}.md"
category=(${1//-/ })
category=${category[0]}
tag=${category[1]}

if [[ ! -e "$(eval echo $sitedir/$postfile)" ]]; then
    eval cd $sitedir

[[ $category == "papers" ]] && papertag=$tag || papertag="bibtag"
cat << EOF  > $postfile
---
layout: post
tags: [$category,$tag]
category: $category
---

## ${tag}

{% cite $papertag %}


References:

{% bibliography --cited %}

EOF
    gvim $postfile
else
    echo "$postfile exists! Quitting..."
fi
