#! /bin/bash

sitedir="$HOME/research/_posts"

[[ ! -n "$1" ]] && echo "Missing argument!" && exit 1

date=`date +%Y-%m-%d`
fname="${date}-${1}.md"
category=(${1//-/ })
category=${category[0]}
tag=${category[1]}

if [[ ! -e "$(eval echo $sitedir/$fname)" ]]; then
    eval cd $sitedir

    echo -e "---\n\
layout: post\n\
tags: [$category,$tag]\n\
category: $category\n\
---" > $fname

    gvim $fname
else
    echo "$fname exists! Quitting..."
fi
