#! /bin/bash

#sitedir="$HOME/Ubuntu\ One/github/research/_posts"
sitedir="$HOME/Dropbox/github/research/_posts"

[[ ! -n "$1" ]] && echo "Missing argument!" && exit 1

date=`date +%Y-%m-%d`
fname="$date-$1.md"
project=(${1//-/ })
project=${project[0]}

if [[ ! -e "$(eval echo $sitedir/$fname)" ]]; then
    eval cd $sitedir

    echo -e "---\n\
layout: post\n\
tags: [$project]\n\
category: $project\n\
---" > $fname

    gvim $fname
else
    echo "$fname exists! Quitting..."
fi
