#! /usr/bin/python

import numpy as np
import sys

f = sys.argv[1]
N = int(sys.argv[2])

def runningMean(x, N):
    y = np.zeros((len(x),))
    for ctr in range(len(x)):
        if ctr == 0:
            y[ctr] = x[0]*N
        elif ctr < N:
            y[ctr] = np.sum(x[0:ctr])/ctr*N
        else:
             y[ctr] = np.sum(x[(ctr-N):ctr])
    return y/N

def runningMean2(x, N):
    y = np.zeros((len(x),))
    n = N/2
    for ctr in range(len(x)):
        if ctr <= n:
            y[ctr] = np.sum(x[0:(ctr+n)])/(ctr+n)*(N+1)
        elif n < ctr < len(x)-n:
             y[ctr] = np.sum(x[(ctr-n):(ctr+n)])
        else:
             y[ctr] = np.sum(x[(ctr-n):-1])/(len(x)-ctr+n+1)*(N+1)
    return y/(N+1)

def runningMeanFast(x, N):
    return np.convolve(x, np.ones((N,))/N)[(N-1):]

x = np.loadtxt(f)
ft = f.split('.')
fout = ft[:-1][0] + '_rm' + str(N) + '.xvg' 
np.savetxt(fout,np.column_stack((x[:,0],runningMean2(x[:,1],N))))
print "Written to %s!" %fout

