#! /bin/bash

scriptsdir="$HOME/Documents/scripts/currentscripts"

cd $scriptsdir
rsync -az pd plotall pp ramaplot shannon pd parsescount calcTvAH ../votca-stepwise-script $HOME/sayargroup/

###################################################################
# Scripts to Dropbox
###################################################################
echo -e "\n********************************************************"
echo -e "\t\tScripts to Dropbox"
echo  -e "********************************************************\n"
rsync -az $scriptsdir/ $HOME/Dropbox/scripts/currentscripts
rsync -az $HOME/SIMS/simfiles $HOME/Dropbox/scripts/simfiles

###################################################################
# Radiotray and Chess
###################################################################
Dmiscdir="$HOME/Dropbox/misc"
rsync -az $HOME/.local/share/radiotray/bookmarks.xml $Dmiscdir/Radio-bookmarks.xml
rsync -az $HOME/.bashrc $Dmiscdir/bashrc
rsync -az $HOME/.bash_aliases $Dmiscdir/bash_aliases
rsync -az $HOME/.vmdrc $Dmiscdir/vmdrc
rsync -az $HOME/.vimrc $Dmiscdir/vimrc
rsync -az $HOME/.gnuplot $Dmiscdir/gnuplot
rsync -az $HOME/Documents/Chess $HOME/Dropbox

#echo -e "\n\n********************************************************"
#echo -e "\t\tSyncing to Dropbox"
#echo  -e "********************************************************\n\n"
#rsync -avz $HOME/.tiddlywiki/TiddlySaver.jar $HOME/.tiddlywiki/notes* $HOME/Dropbox/.tiddlywiki/notes/
#rsync -avz $HOME/.research/TiddlySaver.jar $HOME/.research/research* $HOME/Dropbox/.tiddlywiki/research/

githubdir="$HOME/Dropbox/github"
flashdisk=/media/sinan
if [[ -e $flashdisk ]]; then
    echo -e "\n\n********************************************************"
    echo -e "\t\tSyncing to $flashdisk"
    echo  -e "********************************************************\n\n"
    #rsync -avz $HOME/.tiddlywiki/TiddlySaver.jar $HOME/.tiddlywiki/notes* /media/sinan/.tiddlywiki/notes/
    #rsync -avz $HOME/.research/TiddlySaver.jar $HOME/.research/research* /media/sinan/.tiddlywiki/research/
    rsync -az $scriptsdir/ $flashdisk/scripts/
    rsync -az $HOME/SIMS/simfiles $flashdisk/scripts/
    rsync -az $githubdir $flashdisk/github
else
    echo "Skipping $flashdisk..."
fi

###################################################################
# Scripts to github
###################################################################
echo -e "\n********************************************************"
echo -e "\t\tScripts to github"
echo -e "********************************************************\n"
githubdir="$HOME/Dropbox/github/scripts"
echo $githubdir
eval cd "$githubdir"
syncfiles=`find . -maxdepth 1 -type f`
for file in ${syncfiles[@]}; do
    if [[ $file != ./LICENSE && $file != ./README.md ]]; then
	rsync -azr "$scriptsdir/$file" .
    fi
done

eval cd $githubdir/rc-files
# rc-files
rsync -az $HOME/.bashrc bashrc
rsync -az $HOME/.bash_aliases bash_aliases
rsync -az $HOME/.vmdrc vmdrc
rsync -az $HOME/.gnuplot gnuplot
rsync -az $HOME/.vimrc vimrc
rsync -az $HOME/.gvimrc gvimrc
rsync -az $HOME/.tmux.conf tmux.conf

echo "DONE!"
