#! /bin/bash

hom=$PWD
#JOBDIR="$HOME/.lsbatch"
rjobIDs=`bjobs | awk '{if ($1 ~ /^[0-9]/)print $1}'`
dirset=false
showid=false

# COLORS
###################################################################
# Reset
Color_Off='\e[0m'       # Text Reset
# Bold
BBlack='\e[1;30m'       # Black
BRed='\e[1;31m'         # Red
BGreen='\e[1;32m'       # Green
BYellow='\e[1;33m'      # Yellow
BBlue='\e[1;34m'        # Blue
BPurple='\e[1;35m'      # Purple
BCyan='\e[1;36m'        # Cyan
BWhite='\e[1;37m'       # White
###################################################################

printRUN () {
    echo -e "$d\t$BGreen running! $Color_Off\t"
}

printERR () {
    echo -e "$d\t$BRed not running! $Color_Off"
}

findID () {
    local dir=${@:1}
    local id
    id=$(ls -tr $dir/job_*.out | tail -n 1)
    id=$(basename $id) id=${id#job_} id=${id%.out}
    echo $id
}

printID () {
    #id=`grep $1 $JOBDIR/*.out | tail -n 1 | awk '{print $1}'` && id=(${id//:/ }) && id=${id[0]} && id=(${id//\// }) && id=${id[$((${#id[@]}-1))]} && id=${id%.out} && id=(${id//./ }) && id=${id[$((${#id[@]}-1))]}
    #id=$(grep $1 ~/.lsbatch/*.out | tail -n 1  |  awk '{print $1}' | cut -f1 -d : | cut -f5 -d / | cut -f2 -d .)
    #id=$(ls -tr job_*.out | tail -n 1) id=${id#job_} id=${id%.out}
    echo $id
}

containsElement () {
  local e
  for e in "${@:2}"; do [[ "$e" == "$1" ]] && return 0; done
  return 1
}


while [[ $# -ge 1 ]]; do
    case $1 in

        -d)
            directories="$2"
            dirset=true
            shift 2;;

	-id)
	    showid=true
	    shift;;

    esac
done

IDlist=$(squeue --user=$USER -h -o "%.10i %.1t" | awk '$1 ~ /^[0-9]+$/{print $1}')
#runningIDlist=$(squeue --user=$USER -h -o "%.10i %.1t" | awk '$1 ~ /^[0-9]+$/ && $2 == "R" {print $1}')


if [[ `ls -d Lambda_*/ 2>/dev/null` ]] ; then
    for d in Lambda_*;do
	cwd="$hom/$d/4-TI"
	id=$(findID $cwd)
	containsElement $id ${IDlist[@]}
	check=$?
	if [[ $check == 0 ]] ; then
	    printRUN
	    $showid && printID $cwd
	else
	    printERR
	fi
    done
elif [[ `ls -d d?.*/ 2>/dev/null` ]] ; then
    for d in d?.*; do
	cwd="$hom/$d/4-US"
	id=$(findID $cwd)
	containsElement $id ${IDlist[@]}
	check=$?
	if [[ $check == 0 ]] ; then
	    printRUN
	    $showid && printID $cwd
	else
	    printERR
	fi
    done
elif $dirset; then
    for d in ${directories[@]}; do
	id=$(findID $d)
	containsElement $id ${IDlist[@]}
	check=$?
	if [[ $check == 0 ]] ; then
	    printRUN
	    $showid && printID $d
	else
	    printERR
	fi
    done
else 
	id=$(findID $hom)
	containsElement $id ${IDlist[@]}
	check=$?
	if [[ $check == 0 ]] ; then
	    printRUN
	    $showid && printID $PWD
	else
	    printERR
	fi
fi
