#! /bin/bash

hom=$PWD
runningjobIDs=`qstat -u cdalgicdir | awk '{if ($1 ~ /^[0-9]/)print $1}'`
for d in d?.???;do
    cd $d/4-PULL
    JOBNAME=`grep "\-N" xsubmit-mpi  | awk '{print $3}'`
    thelogs=`ls $JOBNAME.o* 2> /dev/null`
    if [[ $thelogs != "" ]]; then
	JOBids=()
	for f in ${thelogs[@]}; do
	    JOBid=${f#$JOBNAME.o}
	    JOBids+=($JOBid)
	done
	max=0
	for id in ${JOBids[@]}; do
	    [[ $id -gt $max ]] && max=$id
	done
	[[ $runningjobIDs =~ $max ]] && echo "$d: running!" || echo "$d: not running!"
    else
	echo "$d: not running!"
    fi
    cd $hom
done


