# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# don't put duplicate lines in the history. See bash(1) for more options
# ... or force ignoredups and ignorespace
#HISTCONTROL=ignoredups:ignorespace
HISTCONTROL=ignoredups

# append to the history file, don't overwrite it
shopt -s histappend
# Combine multiline commands into one in history
shopt -s cmdhist
# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=20000
HISTFILESIZE=10000
export HISTIGNORE="&:ls:[bf]g:exit"
# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# vi mode
#set -o vi

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "$debian_chroot" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
#force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=
    fi
fi

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033\[01;32m\]\u@\h\[\033\[00m\]:\[\033\[01;34m\]\w\[\033\[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

complete -f -X '!*.pdf' mupdf
complete -f -X '!*.corr' ramaplot
complete -f -X '!*.gp' gp

###################################################################
PROMPT_DIRTRIM=2
PS1='\[\e[1;34m\]\w\[\e[m\] \[\e[1;32m\]\$ \[\e[m\]\[\e[1;37m\] '
#PS1='\[\e[1;34m\](${PWD//\// })\[\e[m\] \[\e[1;32m\]\$ \[\e[m\]\[\e[1;37m\] '
#PS1='\[\e[1;34m\]\w\[\e[m\]\n\[\e[1;32m\]\$ \[\e[m\]\[\e[1;37m\] '
#PS1="\e[01;34m# `date +'%Y.%m.%d %R'` \w\[\e[m\]\n\[\e[1;32m\]\$ \[\e[m\]\[\e[1;37m\] "
###################################################################

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
    . /etc/bash_completion
fi


CDPATH=".:~/remote"
export PATH=$PATH:$HOME/Documents/scripts/currentscripts:$HOME/Mendeley/bin
GROMACSDIR=/usr/local/gromacs/gromacs-4.5.6
votcadir=$HOME/Votca/votca-1.2.3-dodebugfixed
source $GROMACSDIR/bin/GMXRC.bash
export GMXLIB=$GROMACSDIR/share/gromacs/top
source $votcadir/bin/VOTCARC.bash
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib:$votcadir/lib64:$votcadir/lib
export MANPATH=/usr/share/man/:/usr/local/gromacs-4.5.6/share/man:/opt/novell/man
#calc(){ echo "scale=2;$@" | bc;}
#calc(){ printf "%.4f\n" `echo $@ |bc -l`;}
calc(){ echo $@ | octave -q;}
shopt -s extglob
export VIMRUNTIME=/usr/share/vim/vimcurrent
alias emerillon='export CLUTTER_VBLANK=none && emerillon'
man () { yelp "man:$@"; }
export SVNROOT=svn+ssh://cdalgicdir@88.255.97.68/home/svnroot
export DSSP=$HOME/Documents/scripts/currentscripts/dsspold
MANPATH=$MANPATH:/usr/local/texlive/2012/texmf/doc/man
INFOPATH=:$INFOPATH:/usr/local/texlive/2012/texmf/doc/info
PATH=$PATH:/usr/local/texlive/2012/bin/x86_64-linux
# beginning CUDA variables
export PATH=$PATH:/usr/local/cuda-5.0/bin
export LD_LIBRARY_PATH=/usr/local/cuda-5.0/lib64:/lib
# end of CUDA variables
## Up Arrow: search and complete from previous history
bind '"\e[A": history-search-backward'
## Down Arrow: search and complete from next history
bind '"\e[B": history-search-forward'
# Ctrl-v: (insert mode) switch to command mode and edit in vi
bind '"\C-v": "\ev"'
function gvim () { (/usr/bin/gvim -f "$@" &) }
export PATH=$PATH:/usr/local/namd/namd-2.9-multicore
export SCHRODINGER=/opt/schrodinger

### FUNCTIONS

# Easy extract
extract () {
  if [ -f "$1" ] ; then
      case "$1" in
          *.tar.bz2)   tar xvjf "$1"    ;;
          *.tar.gz)    tar xvzf "$1"    ;;
          *.bz2)       bunzip2 "$1"     ;;
          *.rar)       rar x "$1"       ;;
          *.gz)        gunzip "$1"      ;;
          *.tar)       tar xvf "$1"     ;;
          *.tbz2)      tar xvjf "$1"    ;;
          *.tgz)       tar xvzf "$1"    ;;
          *.zip)       unzip "$1"       ;;
          *.Z)         uncompress "$1"  ;;
          *.7z)        7z x "$1"        ;;
          *)           echo "don't know how to extract '$1'..." ;;
      esac
  else
      echo "'$1' is not a valid file!"
  fi
}

#Automatically do an ls after each cd
cd() {

   builtin cd "$@"
   [[ $PWD == "$HOME/Downloads" ]] && ls -tr || ls
}

wiki() {
    local link=`wikipedia2text -u "$1"`
    chromium-browser "${link}"
}

fawk() {
    # "fawk file 2 3" prints 2nd and 3rd columns of
    # file w/o comment lines [@|#]
    [[ $1 == "-p" ]] && option="-p" && shift
    local file="$1" && shift
    if [[ $# -gt 1 ]]; then
	local columns="\$${1}" && shift
	local nargs="$#"
	local nargs=$((nargs-1))
	for i in $@; do
	    local columns=$columns",\$${i}"
	done
    elif [[ $# -eq 1 ]]; then
	local columns="\$${1}"
    else
	echo "Error with number of arguments!"
	exit 1
    fi
    local first="awk '{ if ( \$1 !~ /^[@|#]/) print "
    local last="}'"
    #local cmd="${first}\$${2}${last}"
    local cmd="${first}${columns}${last}"
    [[ $option == "-p" ]] && echo "# $cmd $file"
    eval $cmd $file
}

function pawk {
    local first="awk '{ if ( \$1 !~ /^[@|#]/) print "
    local last="}'"
    local cmd="${first}\$${1}${last}"
    eval $cmd
}
alias alert_helper='history|tail -n1|sed -e "s/^\s*[0-9]\+\s*//" -e "s/;\s*alert$//"'
alias alert='notify-send -i /usr/share/icons/gnome/32x32/apps/gnome-terminal.png "[$?] $(alert_helper)"'
