syntax enable
set background=dark
set guioptions-=T

if matchstr(expand("%"),".*\.md") != ""
    colorscheme darkdevel
    set guifont=Ubuntu\ Mono\ 15
    :au BufRead *.tex set spell
    :highlight SpellBad gui=underline guibg=NONE guifg=red
else
    "colorscheme moria, twilight, solarized, inkpot, corporation, monokai,
    "jellybeans
    colorscheme corporation
    set guifont=Inconsolata\ 16
    "set guifont=Monaco\ 13
endif

"let g:fullscreen = 1
:au BufRead *.tex set spell
:highlight SpellBad gui=underline guibg=NONE guifg=red
if matchstr(expand("%"),".*\.tex") != ""
"if matchstr(expand("%"),"manuscript\.tex$") != ""
    :iab teh the
    :iab aa amino-acid
    :iab hfl hydrophilic
    :iab hfb hydrophobic
    :iab amf amphiphilic
    :iab ss secondary structure
    :iab sc sidechain
    :iab bb backbone
    :iab com1 center of mass
    :iab bs beta-sheet
    :iab rc random-coil
    :iab ah $\alpha$-helix
    :iab hh half-helix
    :iab ahc $\alpha$-helical
    :iab 1bw bulk water
    :iab 1int air/water interface
    :iab 1pmf potential of mean force
    :iab pp peptide
    :iab 1leu leucine
    :iab 1lys lysine
    :iab KL LK$\alpha$14
    :iab ie i.e.
    :iab adn and
    :iab ii4 \emph{CN$_i$-CN$_{i+4}$}
    :iab ca1 C$_{\alpha}$
    :iab cb1 C$_{\beta}$
    ":map <F2> viWB<ESC><ESC>i\emph{<ESC>Ea}<ESC>
endif
