syntax enable
set background=dark
set guioptions-=T

if matchstr(expand("%"),".*\.md") != ""
    colorscheme darkdevel
    set guifont=Ubuntu\ Mono\ 15
else
    "colorscheme moria, twilight, solarized, inkpot, corporation
    colorscheme jellybeans
    set guifont=Inconsolata\ 15
    "set guifont=Monaco\ 13
endif

"let g:fullscreen = 1
:au BufRead *.tex set spell
:highlight SpellBad gui=underline guibg=NONE guifg=red
if matchstr(expand("%"),".*\.tex") != ""
"if matchstr(expand("%"),"manuscript\.tex$") != ""
    :iab teh the
    :iab aa amino-acid
    :iab hfl hydrophilic
    :iab hfb hydrophobic
    :iab amf amphiphilic
    :iab ss secondary structure
    :iab sc sidechain
    :iab bb backbone
    :iab com center of mass
    :iab bs beta-sheet
    :iab rc random-coil
    :iab ah alpha-helix
    :iab hh half-helix
    :iab ahc alpha-helical
    :iab bw bulk water
    :iab int air/water interface
    :iab pmf potential of mean force
    :iab pp peptide
    :iab leu leucine
    :iab lys lysine
    :iab KL LK
    :iab ie i.e.
    :iab adn and
    :map <F2> viwb<ESC><ESC>i\emph{<ESC>ea}<ESC>
endif
