#! /bin/bash

me=`whoami`
shortme="${me:0:8}"
jobs="$HOME/.jobs"
showq > $jobs
sed -i 's/USERNAME/JOBNAME/g' $jobs
JOBIDs=`egrep "^[0-9]+.*${shortme}" $jobs | awk '{print $1}'`

c=0
for id in ${JOBIDs[@]}; do
    JOBNAME=`checkjob $id | grep "AName:" | awk '{print $2}'`
    sed -i "s/$id.*$shortme/$id\t\t$JOBNAME/" $jobs
done

cat $jobs
